### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by dmgcodevil** [jboner/akka-crdt#3]
Hi, how i can start participate in this project in order to contribute it

Thanks.

**Comment by patriknw** [comment]
Hi, contributions would be great. This project is currently moving over to https://github.com/akka/akka/
The pull request for including it in Akka is here: https://github.com/akka/akka/pull/17499

Do you have anything specific that you would like to work on? Anything that you would like to improve?

**Comment by patriknw** [comment]
Hi again, I thought this issue was in https://github.com/patriknw/akka-data-replication

jboner/akka-crdt has evolved into patriknw/akka-data-replication, which is now incorporated in akka/akka.

**Comment by dmgcodevil** [comment]
Hi, so now this project is a part of akka, right ? What tasks do you have ? I'm familiar with akka, scala, more less with CRDT (theory). What plans do you have for the near future ?

**Comment by patriknw** [comment]
Yes, it will be part of Akka 2.4. We are about to merge it to master any day now. It is currently in this pull request: https://github.com/akka/akka/pull/17499

My current plan is to gather user feedback and see what needs improvements.

I'm sure there are more data types that can be interesting to add. Performance improvements might also be needed.

We should continue the discussion in one of the Akka channels.
[akka-dev](https://groups.google.com/forum/#!forum/akka-dev) mailing list is for discussing development of Akka. So is [akka-dev gitter room](https://gitter.im/akka/dev).

Looking forward to your feedback and contributions.

**Comment by naxhh** [comment]
@patriknw maybe would be a good idea to add in the README that people should check akka project?

I did miss the point that akka already had this code :)

**Comment by patriknw** [comment]
@jboner perhaps add a note to the readme (see above)?
